//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAuthenticator.FramworkApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyAuthenticator.FramworkApp.Properties.ResourcesEn", typeof(ResourcesEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept_ {
            get {
                return ResourceManager.GetString("Accept_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        internal static string Are_you_sure_to_delete_ {
            get {
                return ResourceManager.GetString("Are you sure to delete?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the database? All current information will be deleted!.
        /// </summary>
        internal static string Are_you_sure_to_delete_the_database__All_current_information_will_be_deleted_ {
            get {
                return ResourceManager.GetString("Are you sure to delete the database? All current information will be deleted!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to restore? All current information will be deleted!.
        /// </summary>
        internal static string Are_you_sure_to_restore__All_current_information_will_be_deleted_ {
            get {
                return ResourceManager.GetString("Are you sure to restore? All current information will be deleted!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup/restore or change database.
        /// </summary>
        internal static string BackupRestoreChange {
            get {
                return ResourceManager.GetString("BackupRestoreChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel_ {
            get {
                return ResourceManager.GetString("Cancel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change camera.
        /// </summary>
        internal static string Change_camera {
            get {
                return ResourceManager.GetString("Change camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change database path.
        /// </summary>
        internal static string Change_database_path {
            get {
                return ResourceManager.GetString("Change database path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string Change_language {
            get {
                return ResourceManager.GetString("Change language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check authentication when.
        /// </summary>
        internal static string Check_authentication_when {
            get {
                return ResourceManager.GetString("Check authentication when", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates when start.
        /// </summary>
        internal static string Check_updates_when_start {
            get {
                return ResourceManager.GetString("Check updates when start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear database.
        /// </summary>
        internal static string Clear_database {
            get {
                return ResourceManager.GetString("Clear database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to the clipboard.
        /// </summary>
        internal static string Copied_to_the_clipboard {
            get {
                return ResourceManager.GetString("Copied to the clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy dynamic password.
        /// </summary>
        internal static string Copy_dynamic_password {
            get {
                return ResourceManager.GetString("Copy dynamic password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy secret key.
        /// </summary>
        internal static string Copy_secret_key {
            get {
                return ResourceManager.GetString("Copy secret key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is saved.
        /// </summary>
        internal static string Data_is_saved {
            get {
                return ResourceManager.GetString("Data is saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database_ {
            get {
                return ResourceManager.GetString("Database_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database path.
        /// </summary>
        internal static string Database_path {
            get {
                return ResourceManager.GetString("Database path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic password.
        /// </summary>
        internal static string Dynamic_password {
            get {
                return ResourceManager.GetString("Dynamic password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit_ {
            get {
                return ResourceManager.GetString("Edit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get backup.
        /// </summary>
        internal static string Get_backup {
            get {
                return ResourceManager.GetString("Get backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the new update.
        /// </summary>
        internal static string Get_the_new_update {
            get {
                return ResourceManager.GetString("Get the new update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input control.
        /// </summary>
        internal static string Input_control {
            get {
                return ResourceManager.GetString("Input control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version\t{Resources.Version}\nUpdate version\t{UpdateVersion}\nShould the update be performed?.
        /// </summary>
        internal static string IsGetUpdate {
            get {
                return ResourceManager.GetString("IsGetUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move row.
        /// </summary>
        internal static string Move_row {
            get {
                return ResourceManager.GetString("Move row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is duplicate.
        /// </summary>
        internal static string Name_is_duplicate {
            get {
                return ResourceManager.GetString("Name is duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty.
        /// </summary>
        internal static string Name_is_empty {
            get {
                return ResourceManager.GetString("Name is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No camera found!.
        /// </summary>
        internal static string No_camera_found {
            get {
                return ResourceManager.GetString("No camera found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no connection to server.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open database path.
        /// </summary>
        internal static string OpenDatabasePath {
            get {
                return ResourceManager.GetString("OpenDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password_ {
            get {
                return ResourceManager.GetString("Password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is wrong.
        /// </summary>
        internal static string Password_is_wrong {
            get {
                return ResourceManager.GetString("Password is wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not entered.
        /// </summary>
        internal static string Password_not_entered {
            get {
                return ResourceManager.GetString("Password not entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not the same.
        /// </summary>
        internal static string Passwords_are_not_the_same {
            get {
                return ResourceManager.GetString("Passwords are not the same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous password.
        /// </summary>
        internal static string Previous_password {
            get {
                return ResourceManager.GetString("Previous password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous password is wrong.
        /// </summary>
        internal static string Previous_password_is_wrong {
            get {
                return ResourceManager.GetString("Previous password is wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qr-Code.
        /// </summary>
        internal static string Qr_Code {
            get {
                return ResourceManager.GetString("Qr-Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Qr-Code from camera.
        /// </summary>
        internal static string Read_QrCode_from_camera {
            get {
                return ResourceManager.GetString("Read QrCode from camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Qr-Code from file.
        /// </summary>
        internal static string Read_QrCode_from_file {
            get {
                return ResourceManager.GetString("Read QrCode from file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Qr-Code from screen.
        /// </summary>
        internal static string Read_QrCode_from_screen {
            get {
                return ResourceManager.GetString("Read QrCode from screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        internal static string Repeat_password {
            get {
                return ResourceManager.GetString("Repeat password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backup.
        /// </summary>
        internal static string Restore_backup {
            get {
                return ResourceManager.GetString("Restore backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row number.
        /// </summary>
        internal static string Row_number {
            get {
                return ResourceManager.GetString("Row number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowNumber is empty.
        /// </summary>
        internal static string RowNumber_is_empty {
            get {
                return ResourceManager.GetString("RowNumber is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data.
        /// </summary>
        internal static string Save_data {
            get {
                return ResourceManager.GetString("Save data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret key.
        /// </summary>
        internal static string Secret_key {
            get {
                return ResourceManager.GetString("Secret key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret key is empty.
        /// </summary>
        internal static string Secret_key_is_empty {
            get {
                return ResourceManager.GetString("Secret key is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_ {
            get {
                return ResourceManager.GetString("Settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dynamic password.
        /// </summary>
        internal static string Show_dynamic_password {
            get {
                return ResourceManager.GetString("Show dynamic password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Qr-Code of secret key.
        /// </summary>
        internal static string Show_QrCode_of_secret_key {
            get {
                return ResourceManager.GetString("Show_QrCode_of_secret_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show secret key.
        /// </summary>
        internal static string Show_secret_key {
            get {
                return ResourceManager.GetString("Show secret key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is already created.
        /// </summary>
        internal static string The_database_is_already_created {
            get {
                return ResourceManager.GetString("The database is already created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software is updated.
        /// </summary>
        internal static string The_software_is_updated {
            get {
                return ResourceManager.GetString("The software is updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no row to change.
        /// </summary>
        internal static string There_is_no_row_to_move {
            get {
                return ResourceManager.GetString("There is no row to move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        internal static string Two_factor_authentication {
            get {
                return ResourceManager.GetString("Two-factor authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
