//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAuthenticator.FramworkApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesFa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesFa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyAuthenticator.FramworkApp.Properties.ResourcesFa", typeof(ResourcesFa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید.
        /// </summary>
        internal static string Accept_ {
            get {
                return ResourceManager.GetString("Accept_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف اطمینان دارید؟.
        /// </summary>
        internal static string Are_you_sure_to_delete_ {
            get {
                return ResourceManager.GetString("Are you sure to delete?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف پایگاه داده اطمینان دارید؟ تمامی اطلاعات حاضر حذف خواهد شد!.
        /// </summary>
        internal static string Are_you_sure_to_delete_the_database__All_current_information_will_be_deleted_ {
            get {
                return ResourceManager.GetString("Are you sure to delete the database? All current information will be deleted!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از بازیابی نسخه پشتیبان اطمینان دارید؟ تمامی اطلاعات حاضر حذف خواهد شد!.
        /// </summary>
        internal static string Are_you_sure_to_restore__All_current_information_will_be_deleted_ {
            get {
                return ResourceManager.GetString("Are you sure to restore? All current information will be deleted!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت/بازیابی یا تغییر مسیر پایگاه داده.
        /// </summary>
        internal static string BackupRestoreChange {
            get {
                return ResourceManager.GetString("BackupRestoreChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string Cancel_ {
            get {
                return ResourceManager.GetString("Cancel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر دوربین.
        /// </summary>
        internal static string Change_camera {
            get {
                return ResourceManager.GetString("Change camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر مسیر پایگاه داده.
        /// </summary>
        internal static string Change_database_path {
            get {
                return ResourceManager.GetString("Change database path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر زبان.
        /// </summary>
        internal static string Change_language {
            get {
                return ResourceManager.GetString("Change language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر کلمه عبور.
        /// </summary>
        internal static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی احراز هویت در زمان.
        /// </summary>
        internal static string Check_authentication_when {
            get {
                return ResourceManager.GetString("Check authentication when", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی آپدیت هنگام شروع.
        /// </summary>
        internal static string Check_updates_when_start {
            get {
                return ResourceManager.GetString("Check updates when start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاک کردن پایگاه داده.
        /// </summary>
        internal static string Clear_database {
            get {
                return ResourceManager.GetString("Clear database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در کلیپ برد کپی شد.
        /// </summary>
        internal static string Copied_to_the_clipboard {
            get {
                return ResourceManager.GetString("Copied to the clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کپی کلمه عبور پویا.
        /// </summary>
        internal static string Copy_dynamic_password {
            get {
                return ResourceManager.GetString("Copy dynamic password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کپی کد امنیتی.
        /// </summary>
        internal static string Copy_secret_key {
            get {
                return ResourceManager.GetString("Copy secret key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت ذخیره شد.
        /// </summary>
        internal static string Data_is_saved {
            get {
                return ResourceManager.GetString("Data is saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایگاه داده.
        /// </summary>
        internal static string Database_ {
            get {
                return ResourceManager.GetString("Database_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر پایگاه داده.
        /// </summary>
        internal static string Database_path {
            get {
                return ResourceManager.GetString("Database path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور پویا.
        /// </summary>
        internal static string Dynamic_password {
            get {
                return ResourceManager.GetString("Dynamic password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        internal static string Edit_ {
            get {
                return ResourceManager.GetString("Edit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت نسخه پشتیبان.
        /// </summary>
        internal static string Get_backup {
            get {
                return ResourceManager.GetString("Get backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت آپدیت جدید.
        /// </summary>
        internal static string Get_the_new_update {
            get {
                return ResourceManager.GetString("Get the new update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنترل ورودی.
        /// </summary>
        internal static string Input_control {
            get {
                return ResourceManager.GetString("Input control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه فعلی\t{Resources.Version}\nنسخه آپدیت\t{UpdateVersion}\nآیا آپدیت انجام شود؟.
        /// </summary>
        internal static string IsGetUpdate {
            get {
                return ResourceManager.GetString("IsGetUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جابجایی ردیف.
        /// </summary>
        internal static string Move_row {
            get {
                return ResourceManager.GetString("Move row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام تکراری است.
        /// </summary>
        internal static string Name_is_duplicate {
            get {
                return ResourceManager.GetString("Name is duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام وارد نشده.
        /// </summary>
        internal static string Name_is_empty {
            get {
                return ResourceManager.GetString("Name is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوربینی پیدا نشد!.
        /// </summary>
        internal static string No_camera_found {
            get {
                return ResourceManager.GetString("No camera found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط با سرور وجود ندارد.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باز کردن مسیر پایگاه داده.
        /// </summary>
        internal static string OpenDatabasePath {
            get {
                return ResourceManager.GetString("OpenDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        internal static string Password_ {
            get {
                return ResourceManager.GetString("Password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور نادرست است.
        /// </summary>
        internal static string Password_is_wrong {
            get {
                return ResourceManager.GetString("Password is wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور وارد نشده.
        /// </summary>
        internal static string Password_not_entered {
            get {
                return ResourceManager.GetString("Password not entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبورها یکسان نیستند.
        /// </summary>
        internal static string Passwords_are_not_the_same {
            get {
                return ResourceManager.GetString("Passwords are not the same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور قبلی.
        /// </summary>
        internal static string Previous_password {
            get {
                return ResourceManager.GetString("Previous password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور قبلی نادرست است.
        /// </summary>
        internal static string Previous_password_is_wrong {
            get {
                return ResourceManager.GetString("Previous password is wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارکد.
        /// </summary>
        internal static string Qr_Code {
            get {
                return ResourceManager.GetString("Qr-Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خواندن بارکد از دوربین.
        /// </summary>
        internal static string Read_QrCode_from_camera {
            get {
                return ResourceManager.GetString("Read QrCode from camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خواندن بارکد از فایل.
        /// </summary>
        internal static string Read_QrCode_from_file {
            get {
                return ResourceManager.GetString("Read QrCode from file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خواندن بارکد از صفحه نمایش.
        /// </summary>
        internal static string Read_QrCode_from_screen {
            get {
                return ResourceManager.GetString("Read QrCode from screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور.
        /// </summary>
        internal static string Repeat_password {
            get {
                return ResourceManager.GetString("Repeat password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی نسخه پشتیبان.
        /// </summary>
        internal static string Restore_backup {
            get {
                return ResourceManager.GetString("Restore backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ردیف.
        /// </summary>
        internal static string Row_number {
            get {
                return ResourceManager.GetString("Row number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ردیف وارد نشده.
        /// </summary>
        internal static string RowNumber_is_empty {
            get {
                return ResourceManager.GetString("RowNumber is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره اطلاعات.
        /// </summary>
        internal static string Save_data {
            get {
                return ResourceManager.GetString("Save data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی.
        /// </summary>
        internal static string Secret_key {
            get {
                return ResourceManager.GetString("Secret key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی.
        /// </summary>
        internal static string Secret_key_is_empty {
            get {
                return ResourceManager.GetString("Secret key is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        internal static string Settings_ {
            get {
                return ResourceManager.GetString("Settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش کلمه عبور پویا.
        /// </summary>
        internal static string Show_dynamic_password {
            get {
                return ResourceManager.GetString("Show dynamic password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش بارکد کد امنیتی.
        /// </summary>
        internal static string Show_QrCode_of_secret_key {
            get {
                return ResourceManager.GetString("Show_QrCode_of_secret_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش کد امنیتی.
        /// </summary>
        internal static string Show_secret_key {
            get {
                return ResourceManager.GetString("Show secret key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایگاه داده قبلا ایجاد شده است.
        /// </summary>
        internal static string The_database_is_already_created {
            get {
                return ResourceManager.GetString("The database is already created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرم افزار آپدیت است.
        /// </summary>
        internal static string The_software_is_updated {
            get {
                return ResourceManager.GetString("The software is updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیفی برای جابجایی وجود ندارد.
        /// </summary>
        internal static string There_is_no_row_to_move {
            get {
                return ResourceManager.GetString("There is no row to move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبارسنجی دوعاملی.
        /// </summary>
        internal static string Two_factor_authentication {
            get {
                return ResourceManager.GetString("Two-factor authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
