using System;
using System.Collections.Generic;
using System.Windows.Forms;
using MyAuthenticator.FramworkApp.Properties;
using MyAuthenticator.FramworkData.Context;
using MyAuthenticator.FramworkData.Repository;
using MyAuthenticator.FramworkLibrary;
using System.Drawing;

namespace MyAuthenticator.FramworkApp
{
    public partial class frmMain : Form
    {
        private PasswordDTO CurrentPasswordForShow;

        public frmMain()
        {
            InitializeComponent();
            ClearAutoGeneratedColumnsOfGrid();
            this.SetIcon();
        }

        private void ClearAutoGeneratedColumnsOfGrid()
        {
            var columnCount = grdPassword.ColumnCount;
            var normalCount = 7;
            if (columnCount > normalCount)
            {
                for (int i = columnCount - 1; i > normalCount - 1; --i)
                {
                    grdPassword.Columns[i].Name = string.Empty;
                    grdPassword.Columns[i].DataPropertyName = string.Empty;
                    grdPassword.Columns[i].HeaderText = string.Empty;
                    grdPassword.Columns[i].Visible = false;
                }
            }
        }

        private void frmMain_Load(object sender, EventArgs e)
        {
            SetToolTip();
            SetSettings();
            SearchData(null, null);
        }

        private void SetSettings()
        {
            ChangeImageBtnIsGetPasswordForShowSecretKey(GetIsGetPasswordForShowSecretKeys());
            ChangeImageBtnIsGetPasswordForShowDynamicPasswordKey(GetIsGetPasswordForShowDynamicPasswords());
            ChangeImageBtnIsGetPasswordForRestoreBackup(GetIsGetPasswordForRestoreBackup());
        }

        private void ChangeImageBtnIsGetPasswordForRestoreBackup(bool isActive)
        {
            btnIsGetPasswordForRestoreBackup.Image = isActive ? Resources.Tick : null;
        }

        private void ChangeImageBtnIsGetPasswordForShowDynamicPasswordKey(bool isActive)
        {
            btnIsGetPasswordForShowDynamicPasswordKey.Image = isActive ? Resources.Tick : null;
        }

        private void ChangeImageBtnIsGetPasswordForShowSecretKey(bool isActive)
        {
            btnIsGetPasswordForShowSecretKey.Image = isActive ? Resources.Tick : null;
        }

        private void SetToolTip()
        {
            ToolTip toolTip = new ToolTip();
            toolTip.SetToolTip(btnShowSecretKey, btnShowSecretKey.Tag.ToString());
            toolTip.SetToolTip(btnCopySecretKey, btnCopySecretKey.Tag.ToString());
            toolTip.SetToolTip(btnQrCodeSecretKey, btnQrCodeSecretKey.Tag.ToString());
            toolTip.SetToolTip(btnAdd, btnAdd.Tag.ToString());
            toolTip.SetToolTip(btnEdit, btnEdit.Tag.ToString());
            toolTip.SetToolTip(btnDelete, btnDelete.Tag.ToString());
            toolTip.SetToolTip(btnCancel, btnCancel.Tag.ToString());
            toolTip.SetToolTip(btnAcc, btnAcc.Tag.ToString());
            toolTip.SetToolTip(btnGetOtpFromFile, btnGetOtpFromFile.Tag.ToString());
        }

        private void AddBinding()
        {
            txtName.DataBindings.Add("Text", bsPassword, "Title");
        }

        private static PasswordDTO GetPasswordDTO(Password p)
        {
            return new PasswordDTO()
            {
                PasswordID = p.PasswordID,
                RowNumber = p.RowNumber,
                Title = p.Name,
                SecretKey = p.SecretKey,
                Counter = null,
            };
        }

        private void ClearBinding()
        {
            txtName.DataBindings.Clear();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            EnableAddOrEdit(enable: true);

            ClearBinding();

            ClearHeader(isClearSecretKeyOnly: false);

            btnAcc.Tag = btnAdd.Name;
        }

        private void ClearHeader(bool? isClearSecretKeyOnly = null)
        {
            if (isClearSecretKeyOnly == null || isClearSecretKeyOnly == false)
            {
                txtName.ResetText();
            }
            txtSecretKey.ResetText();
        }

        private void EnableAddOrEdit(bool enable)
        {
            txtName.ReadOnly = !enable;
            txtSecretKey.ReadOnly = !enable;
            btnGetOtpFromFile.Enabled = enable;
            btnShowSecretKey.Enabled = !enable;
            btnCopySecretKey.Enabled = !enable;
            btnQrCodeSecretKey.Enabled = !enable;
            txtNameSearch.Enabled = !enable;
            grdPassword.Enabled = !enable;
            btnAdd.Enabled = !enable;
            btnEdit.Enabled = !enable;
            btnDelete.Enabled = !enable;
            grdPassword.Enabled = !enable;
            txtName.Enabled = enable;
            txtSecretKey.Enabled = enable;
            btnCopySecretKey.Enabled = !enable;
            btnCopyPassword.Enabled = !enable;
            btnCancel.Enabled = enable;
            btnAcc.Enabled = enable;
        }

        private void btnEdit_Click(object sender, EventArgs e)
        {
            EnableAddOrEdit(enable: true);

            ClearBinding();

            ClearHeader(isClearSecretKeyOnly: true);

            btnAcc.Tag = btnEdit.Name;
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            EnableAddOrEdit(enable: false);

            ClearHeader();

            btnAcc.Tag = string.Empty;

            SearchData(null, null);
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            var currentPassword = GetCurrentPassword();
            if (currentPassword != null)
            {
                var dialogResult = RtlMessageBox.Show(Resources.Are_you_sure_to_delete_,
                                    $"{Resources.Delete} {currentPassword.Title}",
                                    MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                if (dialogResult == DialogResult.Yes)
                {
                    PasswordRepository.Delete(currentPassword.PasswordData);
                    btnCancel_Click(null, null);
                }
            }
        }

        private PasswordDTO GetCurrentPassword(bool isShowPassword = false)
        {
            var currentPassword = bsPassword.Current as PasswordDTO;
            if (currentPassword != null)
            {
                if (!isShowPassword)
                {
                    return currentPassword;
                }
                else if (!GetIsGetPasswordForShowDynamicPasswords() || Program.OpenLoginForm())
                {
                    return currentPassword;
                }
                else
                {
                    return null;
                }
            }
            return currentPassword;
        }

        private void btnAcc_Click(object sender, EventArgs e)
        {
            if (ControlAddOrEdit())
            {
                var password = new PasswordDTO()
                {
                    PasswordID = IsAddMode() == true ? new Guid() :
                    IsEditMode() == true ? GetCurrentPassword().PasswordID :
                    new Guid(),
                    Title = txtName.Text,
                    SecretKey = TOTP.GetSecretKey(txtSecretKey.Text)
                };
                if (!PasswordRepository.IsDuplicate(txtName.Text, password.PasswordID))
                {
                    PasswordRepository.AddOrEdit(password.PasswordData);
                    btnCancel_Click(null, null);
                }
                else
                {
                    RtlMessageBox.Show(Resources.Name_is_duplicate, Resources.Input_control,
                                MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }
            }
        }

        public bool? IsAddMode()
        {
            return btnAcc.Tag.ToString() == btnAdd.Name ? true :
                btnAcc.Tag.ToString() == string.Empty ? (bool?)null :
                false;
        }

        public bool? IsEditMode()
        {
            return btnAcc.Tag.ToString() == btnEdit.Name ? true :
                btnAcc.Tag.ToString() == string.Empty ? (bool?)null :
                false;
        }

        private bool ControlAddOrEdit()
        {
            if (string.IsNullOrEmpty(txtName.Text))
            {
                RtlMessageBox.Show(Resources.Name_is_empty, Resources.Input_control,
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
                return false;
            }
            else if (IsAddMode() == true && string.IsNullOrEmpty(txtSecretKey.Text))
            {
                RtlMessageBox.Show(Resources.Secret_key_is_empty, Resources.Input_control,
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
                return false;
            }
            return true;
        }

        private void btnShowPassword_Click(object sender, EventArgs e)
        {
            if (CurrentPasswordForShow == null || !timerClearPassword.Enabled)
            {
                CurrentPasswordForShow = GetCurrentPassword(isShowPassword: true);
                if (CurrentPasswordForShow != null)
                {
                    var totp = new TOTP(CurrentPasswordForShow.SecretKey);
                    CurrentPasswordForShow.PasswordString = totp.ComputeTotp();
                    var intervalSeconds = totp.RemainingSeconds();
                    var interval = TimeSpan.FromSeconds(intervalSeconds).TotalMilliseconds;
                    CurrentPasswordForShow.Counter = intervalSeconds;
                    timerClearPassword.Interval = (int)interval;
                    timerClearPassword.Enabled = true;
                    timerClearPassword.Start();
                    timerCounter.Enabled = true;
                    timerCounter.Start();
                }
            }
            else {}
        }

        private void timerClearPassword_Tick(object sender, EventArgs e)
        {
            CurrentPasswordForShow.PasswordString = PasswordDTO.PasswordStar;
            CurrentPasswordForShow.Counter = null;
            grdPassword.Refresh();
            grdPassword.AutoResizeColumns();
            timerClearPassword.Stop();
            timerClearPassword.Enabled = false;
            CurrentPasswordForShow = null;
        }

        private void timerCounter_Tick(object sender, EventArgs e)
        {
            if (CurrentPasswordForShow?.Counter > 1)
            {
                --CurrentPasswordForShow.Counter;
                grdPassword.Refresh();
            }
            else
            {
                if (CurrentPasswordForShow != null)
                {
                    CurrentPasswordForShow.Counter = null;
                }
                grdPassword.Refresh();
                timerCounter.Stop();
                timerCounter.Enabled = false;
            }
            grdPassword.AutoResizeColumns();
        }

        private void btnCopyPassword_Click(object sender, EventArgs e)
        {
            var currentPassword = GetCurrentPassword(isShowPassword: true);
            if (currentPassword != null)
            {
                var totp = new TOTP(currentPassword.SecretKey);
                var passwordString = totp.ComputeTotp();
                Clipboard.SetText(passwordString);
                RtlMessageBox.Show(Resources.Copied_to_the_clipboard, string.Empty, MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void btnShowSecretKey_Click(object sender, EventArgs e)
        {
            txtSecretKey.Text = GetCurrentSecretKey(out string title);
        }

        private string GetCurrentSecretKey(out string title)
        {
            var currentPassword = GetCurrentPassword();
            string secretKey = null;
            title = null;
            if (currentPassword != null && (!GetIsGetPasswordForShowSecretKeys() || Program.OpenLoginForm()))
            {
                secretKey = TOTP.GetSecretKey(currentPassword.SecretKey);
                title = currentPassword.Title;
            }

            return secretKey;
        }

        private void btnCopySecretKey_Click(object sender, EventArgs e)
        {
            var secretKey = GetCurrentSecretKey(out string title);
            if (secretKey != null)
            {
                Clipboard.SetText(secretKey);
                RtlMessageBox.Show(Resources.Copied_to_the_clipboard, string.Empty, MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void bsPassword_CurrentChanged(object sender, EventArgs e)
        {
            txtSecretKey.ResetText();
        }

        private void SearchData(object sender, EventArgs e)
        {
            var name = txtNameSearch.Text;
            ClearBinding();
            var searchList = new List<PasswordDTO>();
            {
                var list = new List<Password>();
                if (string.IsNullOrEmpty(name))
                {
                    list = PasswordRepository.Get();
                }
                else
                {
                    list = PasswordRepository.Search(name);
                }
                list = PasswordRepository.OrderByRowNumber(list);
                list.ForEach(p => searchList.Add(GetPasswordDTO(p)));
            }
            bsPassword.DataSource = searchList;
            grdPassword.AutoResizeColumns();
            AddBinding();
        }

        private void btnChangePassword_Click(object sender, EventArgs e)
        {
            using (var frm = new frmLogin(ChangePasswordMode.Change))
            {
                frm.Text = btnChangePassword.Text;
                var result = frm.ShowDialog();
                if (result == DialogResult.OK)
                {
                    RtlMessageBox.Show(Resources.Data_is_saved,
                                    Resources.Save_data,
                                    MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
        }

        private void btnBackup_Click(object sender, EventArgs e)
        {
            if (ColtrolAutentication())
            {
                saveBackupDialog.Title = btnBackup.Text;
                if (saveBackupDialog.ShowDialog() == DialogResult.OK)
                {
                    AuthenticatorRepository.Backup(saveBackupDialog.FileName);
                }
            }
        }

        private bool ColtrolAutentication()
        {
            return !GetIsGetPasswordForRestoreBackup() || Program.OpenLoginForm();
        }

        private void btnRestore_Click(object sender, EventArgs e)
        {
            if (ColtrolAutentication())
            {
                var dialogResult = RtlMessageBox.Show(Resources.Are_you_sure_to_restore__All_current_information_will_be_deleted_, btnRestore.Text, MessageBoxButtons.YesNo);
                openBackupDialog.Title = btnRestore.Text;
                if (dialogResult == DialogResult.Yes && openBackupDialog.ShowDialog() == DialogResult.OK)
                {
                    AuthenticatorRepository.Restore(openBackupDialog.FileName);
                    AuthenticatorRepository.GetNewModel();
                    Program.Migration();
                    Program.InsertDefaultValue();
                    SetSettings();
                    SearchData(null, null);
                }
            }
        }

        private void btnDeleteDatabase_Click(object sender, EventArgs e)
        {
            if (ColtrolAutentication())
            {
                var dialogResult = RtlMessageBox.Show(Resources.Are_you_sure_to_delete_the_database__All_current_information_will_be_deleted_, btnRestore.Text, MessageBoxButtons.YesNo);
                if (dialogResult == DialogResult.Yes)
                {
                    AuthenticatorRepository.DeleteDatabase();
                    AuthenticatorRepository.CreateDatabase();
                    AuthenticatorRepository.GetNewModel();
                    SearchData(null, null);
                }
            }
        }

        private void btnQrCodeSecretKey_Click(object sender, EventArgs e)
        {
            var secretKey = GetCurrentSecretKey(out string title);
            if (secretKey != null)
            {
                using (var frm = new frmQrCode(title, secretKey))
                {
                    frm.ShowDialog();
                }
            }
        }

        private void btnIsGetPasswordForShowSecretKey_Click(object sender, EventArgs e)
        {
            var isActiveOld = GetIsGetPasswordForShowSecretKeys();
            SettingRepository.UpdateIsGetPasswordForShowSecretKeys(!isActiveOld);
            ChangeImageBtnIsGetPasswordForShowSecretKey(isActive: !isActiveOld);
        }

        private static bool GetIsGetPasswordForShowSecretKeys()
        {
            return SettingRepository.IsGetPasswordForShowSecretKeys();
        }

        private void btnIsGetPasswordForShowDynamicPasswordKey_Click(object sender, EventArgs e)
        {
            var isActiveOld = GetIsGetPasswordForShowDynamicPasswords();
            SettingRepository.UpdateIsGetPasswordForShowDynamicPasswords(!isActiveOld);
            ChangeImageBtnIsGetPasswordForShowDynamicPasswordKey(isActive: !isActiveOld);
        }

        private static bool GetIsGetPasswordForShowDynamicPasswords()
        {
            return SettingRepository.IsGetPasswordForShowDynamicPasswords();
        }

        private void grdPassword_CellContentDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            var currentCell = (sender as DataGridView).CurrentCell;
            var imageCell = (currentCell as DataGridViewImageCell);
            if (imageCell != null)
            {
                var currentPassword = GetCurrentPassword();
                decimal newRow = 0;
                switch (imageCell.Description)
                {
                    case "Up":
                        newRow = PasswordRepository.GetUpDownRowNumber(currentPassword.PasswordData, isUp: true);
                        if (newRow != 0)
                        {
                            PasswordRepository.ChangeRowNumber(currentPassword.PasswordData, newRow);
                            SearchData(null, null);
                        }
                        break;

                    case "Down":
                        newRow = PasswordRepository.GetUpDownRowNumber(currentPassword.PasswordData, isUp: false);
                        if (newRow != 0)
                        {
                            PasswordRepository.ChangeRowNumber(currentPassword.PasswordData, newRow);
                            SearchData(null, null);
                        }
                        break;

                    case "Between":
                        using (var frm = new frmChangeRow(currentPassword))
                        {
                            if (frm.ShowDialog() == DialogResult.OK)
                            {
                                newRow = frm.RowNumber;
                                PasswordRepository.ChangeRowNumber(currentPassword.PasswordData, newRow);
                                SearchData(null, null);
                            }
                        }
                        break;

                    default:
                        break;
                }
            }
        }

        private void btnIsGetPasswordForRestoreBackup_Click(object sender, EventArgs e)
        {
            var isActiveOld = GetIsGetPasswordForRestoreBackup();
            SettingRepository.UpdateIsGetPasswordForRestoreBackup(!isActiveOld);
            ChangeImageBtnIsGetPasswordForRestoreBackup(isActive: !isActiveOld);
        }

        private static bool GetIsGetPasswordForRestoreBackup()
        {
            return SettingRepository.IsGetPasswordForRestoreBackup();
        }

        private void btnGetOtpFromFile_Click(object sender, EventArgs e)
        {
            openImageDialog.Title = btnGetOtpFromFile.Tag.ToString();
            if (openImageDialog.ShowDialog() == DialogResult.OK)
            {
                var otp = TOTP.ReadOtp(openImageDialog.FileName);
                if (otp != null)
                {
                    txtName.Text = otp["Name"];
                    txtSecretKey.Text = otp["Secret"];
                }
            }
        }
    }
}
